version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.7-node-browsers
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 4
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          RACK_ENV: test
          IN_CIRCLE: true
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 1.17.3
          with-cache: false
      - ruby/rspec-test
      - slack/status:
          channel: devs-alerts
          fail_only: true
  notify:
    docker:
      - image: circleci/ruby:2.5.7-node-browsers
    steps:
      - slack/status:
          channel: devs-alerts

workflows:
  version: 2
  build:
    jobs:
      - build
      - notify:
          requires:
            - build
